### ISSUE TITLE
A sample email for contributors to use to ask for participation

### ISSUE THREAD

**Issue by choldgraf** [pyOpenSci/dev_guide#13]
Hey all - I was gonna email a couple of folks to ask if they're interested in helping out with / submitting for / etc pyOpenSci. Figured it'd be easier to create a template email others can use to save folks some time.

**For folks on the project, feel free to edit this to make imrovements!**

---
< short greeting />

I'm writing to see if you'd be interested in participating with [pyOpenSci](http://www.pyopensci.org/), a new community around improving the quality of software in the scientific python stack.

pyOpenSci provides resources, mentoring, and documentation for making scientific python packages more useful and maintainable. It builds off of the successful [rOpenSci](https://ropensci.org/) model, with a Python flavor. It primarily coordinates a review process by which experienced developers in the scientific python ecosystem can provide feedback and suggestions to other (usually fairly small) packages.

You've been in the scientific Python community for some time now, and I think you'd be a great part of the pyOpenSci community. Would you be interested in joining us? Participation can be as small or large as you wish - for example, you could submit your own package for review in pyOpenSci, offer to be a reviewer of someone else's package, or begin attending pyOpenSci planning meetings as we build and refine our processes. We'd just be happy to have you around :-)

< short goodbye />

---

**Comment by choldgraf** [comment]
cc @lwasser who's probably writing these kinds of emails too :-)

(also, feel free to suggest a different place to share this information...I can't think of another place to store this kinda thing in a discoverable place...I think it's the kinda thing we could use a Discourse for, but I can't remember if that's part of the plan or not)

**Comment by lwasser** [comment]
this is much better than what i've been doing @choldgraf thank you for submitting this!! we have been talking about getting discourse setup @kysolvik is going to look into it. do you guys have hosting through jupyter of discourse? and can you customize the domain??

**Comment by choldgraf** [comment]
they've got an open source option that will let you choose your domain as long as it is `discourse.mydomain.org`, that's what we use at `discourse.jupyter.org`
