### ISSUE TITLE
CI setup & Do we need CI for this website build?

### ISSUE THREAD

**Issue by lwasser** [pyOpenSci/dev_guide#15]
1. Currently the CI setup authentication is under @kysolvik username. We probably want to use earth.lab for the time being and then ultimately we should have a pyopensci user that has admin privileges
2. Does the build need to be so complete given gh-pages will auto build markdown files??

**Comment by choldgraf** [comment]
What the build does is auto-generates the markdown files that the site uses (aka, it runs `jupyter-book build .`. Otherwise we'd need to remember to run this each time we update the content and include the changes in the PR.

**Comment by choldgraf** [comment]
just took a look at this again...I think that the circle build in there is actually somewhat unnecessary (it runs the jupyter book test suite, probably because I had copied everything over from the jupyter book repo). We could re-visit the build commands to simplify!

**Comment by choldgraf** [comment]
this is now fixed!
