### ISSUE TITLE
Add installation instructions to the requirement for the pre-submission guideline

### ISSUE THREAD

**Issue by choldgraf** [pyOpenSci/dev_guide#18]
In our review, one of use (hint: it was me) had a really hard time installing the environment needed to run the package. This was partially because there was no installation instructions given. As a pre-requisite for the review process to begin, we should probably ensure that there are at least *some* instructions, and the reviewers can decide if they're "good" or not after they follow them :-)

**Comment by kysolvik** [comment]
This is a really good idea! I'll add some language asap

**Comment by kysolvik** [comment]
Added [some language](https://www.pyopensci.org/dev_guide/packaging/packaging_guide.html#overview) to the very top of the packaging guide (#23). It's mentioned again further down and in the submission checklist issue template.

Do you think this is enough @choldgraf? Are there other places we could emphasize it further? It's currently required as part of the README, so it's possible  that people might see "needs readme", check the box, and move on without thinking about the installation instructions part.

**Comment by choldgraf** [comment]
yep, that works for me!
