### ISSUE TITLE
Specifically requires a markdown README

### ISSUE THREAD

**Issue by kysolvik** [pyOpenSci/dev_guide#32]
It seems like at least restructuredtext would be fine too. I can submit a PR to fix this unless anyone has objections

**Comment by lwasser** [comment]
hey @kysolvik !!! how are things?? are you suggesting that we are a bit too specific in terms of requiring the FORMAT of the readme file to be .md only? i'm very open to .rst as well. do you happen to know if github renders .rst in the same way it does .md on the landing page of a repo? if it's the same i can't think if any reason to not make this pr!!! 

hope all is well!! our BoF is tomorrow! i saw descarte labs is here too :)

**Comment by kysolvik** [comment]
hey @lwasser!! Things are good! Good luck with the BoF tomorrow! Hope it goes great :)

Yeah that's all I'm suggesting. rst does get rendered, actually nbless uses an rst README: https://github.com/py4ds/nbless/blob/master/README.rst

I was thinking pyopensci could just require a README and then suggest restructuredtext or markdown. It looks like there are a few other filetypes that get rendered by github, but those two are the most standard: https://github.com/github/markup

**Comment by lwasser** [comment]
awesome @kysolvik yes, let's adjust the text to allow for format flexibility! i think the only thing we want is something rendered by github (so html would not be useful / usable for example!). thank you for the suggestion!!

and hoping that the BoF goes well today :) the hackmd for it is here: https://hackmd.io/B9zy15QZQTiYXiqRnl0ynA?both

**Comment by choldgraf** [comment]
I believe that this is now explicit in: https://www.pyopensci.org/dev_guide/authoring/overview.html
