### ISSUE TITLE
security alert! rubyzip ?? not sure if this is of concern but it just popped up!

### ISSUE THREAD

**Issue by lwasser** [pyOpenSci/dev_guide#37]
<img width="1154" alt="Screen Shot 2019-09-30 at 3 37 07 PM" src="https://user-images.githubusercontent.com/7649194/65918939-3548ac00-e398-11e9-9e50-641802f5cf0b.png">

**Comment by choldgraf** [comment]
the same thing popped up in jupyter book haha, I just merged in the PR but 🤷‍♂

**Comment by lwasser** [comment]
i wonder if it's that gem.lock file?? i'm not sure we need it in the repo and could maybe add it to .gitignore (not 100% sure) but i know minimal mistakes doesn't have it in their repo. 

we don't either?! 
https://github.com/earthlab/earthlab.github.io/blob/master/.gitignore#L11

**Comment by choldgraf** [comment]
this is no longer an issue w/ the new jupyter book!

**Comment by lwasser** [comment]
yay thank you @choldgraf !!!
