### ISSUE TITLE
Do we need to have a _data file for the TOC?

### ISSUE THREAD

**Issue by lwasser** [pyOpenSci/dev_guide#38]
@choldgraf do we need to populate this sidebar manually with jupyterbook?
just wondering if it's work automating that piece but i'm not familiar enough with the book setup to know whether you'r purposefully setting that manually or not! just curious!

thank you so much for the awesome updates!!!

**Comment by choldgraf** [comment]
yep - you need that file to define the order of the pages in your book.

You can generate one automatically using the filenames with `jupyter-book toc path/to/my_book`

**Comment by lwasser** [comment]
ok great!! i'm pretty sure @kysolvik created it manually! so good to know there is a cli option! maybe we can add that to CI in the future (not a big deal now ). i was just thinking that is we add content there is a manual step here that could get lost!

**Comment by choldgraf** [comment]
this is now fixed!
