### ISSUE TITLE
Consider Restructuring Docs into separate chapters

### ISSUE THREAD

**Issue by lwasser** [pyOpenSci/dev_guide#47]
from @choldgraf 

1. for people developing packages
 * infrastructure requirements, etc
2. about the pyopensci process itself
  * what does the review process look like

* Two guides potentially
    * One that is developer/author-focused
        * Maybe don't use the word "dev_guide", maybe something like "author_guide"?
    * One that is editor/reviewer/process-focused

**Comment by choldgraf** [comment]
This is now done! We still may split into two guides but I think for now we can close the issue until we get a feel for the new structure
